version: '3'

services:

  #Profile
  profile:
    image: nginx
    container_name: profile
    restart: always
    expose:
      - "3000"
    networks:
      - web
    labels:
      - "traefik.backend=profile"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=AddPrefix:/profile"
      - "traefik.port=3000"
      - "traefik.protocol=http"
    volumes:
      - "/cswilson.site/mounts/profile:/usr/share/nginx/html"
   
    #Fitness
  fitness:
    image: nginx
    container_name: fitness
    restart: always
    expose:
      - "3001"
    networks:
      - web
    labels:
      - "traefik.backend=fitness"
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=AddPrefix:/fitness"
      - "traefik.port=3001"
      - "traefik.protocol=http"
    volumes:
      - "/cswilson.site/mounts/fitness:/usr/share/nginx/html"

networks:
  web:
    external: true      
